# Generated by Django 5.2.13 on 2026-05-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=255)),
                ('element_id', models.CharField(blank=True, max_length=255)),
                ('element_class', models.CharField(blank=True, max_length=255)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('target_url', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
