# Generated by Django 5.2.13 on 2026-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_clickevent_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='clicked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='referrer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='referrer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name='DailyClickAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('page', models.CharField(max_length=255)),
                ('element', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('click_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date', 'page', 'element'),
                'constraints': [models.UniqueConstraint(fields=('date', 'page', 'element', 'target_url'), name='unique_daily_click_aggregate')],
            },
        ),
        migrations.CreateModel(
            name='DailyPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=255)),
                ('visit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date', 'path'),
                'constraints': [models.UniqueConstraint(fields=('date', 'path'), name='unique_daily_page_visit')],
            },
        ),
    ]
